# Generated by Django 4.1.4 on 2023-04-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('J2', '0002_alter_intell_policyguidance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intell',
            options={'verbose_name': 'J2 (Intell)', 'verbose_name_plural': 'J2 (Intell)'},
        ),
    ]
